In [0]:
df1 = spark.read.format("json").load("dbfs:/FileStore/shared_uploads/filetechn@gmail.com/people-1.json")

In [0]:
df1.show()

+----+-------+
| age|   name|
+----+-------+
|null|    Fer|
|  20|Michael|
|  15|    Ana|
+----+-------+

In [0]:
display(df1)

age,name
null,Fer
20,Michael
15,Ana

In [0]:
df1.printSchema()

root
 |-- age: long (nullable = true)
 |-- name: string (nullable = true)

In [0]:
df1.columns

Out[5]: ['age', 'name']

In [0]:
df1.describe().show()

+-------+------------------+-------+
|summary|               age|   name|
+-------+------------------+-------+
|  count|                 2|      3|
|   mean|              17.5|   null|
| stddev|3.5355339059327378|   null|
|    min|                15|    Ana|
|    max|                20|Michael|
+-------+------------------+-------+

## CREATE COLUMN

In [0]:
df1.show()

+----+-------+
| age|   name|
+----+-------+
|null|    Fer|
|  20|Michael|
|  15|    Ana|
+----+-------+

In [0]:
df2 = df1.withColumn('newname',df1['name'])

In [0]:
df2.show()

+----+-------+-------+
| age|   name|newname|
+----+-------+-------+
|null|    Fer|    Fer|
|  20|Michael|Michael|
|  15|    Ana|    Ana|
+----+-------+-------+

## CREATE COLUMNS WITH OPERATION

In [0]:
df2.show()

+----+-------+-------+
| age|   name|newname|
+----+-------+-------+
|null|    Fer|    Fer|
|  20|Michael|Michael|
|  15|    Ana|    Ana|
+----+-------+-------+

In [0]:
df_x = df2.withColumn('age_new',df2['age']*2)

In [0]:
df_x.show()

+----+-------+-------+-------+
| age|   name|newname|age_new|
+----+-------+-------+-------+
|null|    Fer|    Fer|   null|
|  20|Michael|Michael|     40|
|  15|    Ana|    Ana|     30|
+----+-------+-------+-------+

# RENAMED COLUMN

In [0]:
df_x.show()

+----+-------+-------+-------+
| age|   name|newname|age_new|
+----+-------+-------+-------+
|null|    Fer|    Fer|   null|
|  20|Michael|Michael|     40|
|  15|    Ana|    Ana|     30|
+----+-------+-------+-------+

In [0]:
df = df_x

In [0]:
df2 = df.withColumnRenamed('age_new','renamed_age')

In [0]:
df2.show()

+----+-------+-------+-----------+
| age|   name|newname|renamed_age|
+----+-------+-------+-----------+
|null|    Fer|    Fer|       null|
|  20|Michael|Michael|         40|
|  15|    Ana|    Ana|         30|
+----+-------+-------+-----------+

## QUERY IN SPARK SQL

In [0]:
df2.show()

+----+-------+-------+-----------+
| age|   name|newname|renamed_age|
+----+-------+-------+-----------+
|null|    Fer|    Fer|       null|
|  20|Michael|Michael|         40|
|  15|    Ana|    Ana|         30|
+----+-------+-------+-----------+

In [0]:
df2.createOrReplaceTempView('data')

In [0]:
query = spark.sql("SELECT * FROM data")

In [0]:
query.show()

+----+-------+-------+-----------+
| age|   name|newname|renamed_age|
+----+-------+-------+-----------+
|null|    Fer|    Fer|       null|
|  20|Michael|Michael|         40|
|  15|    Ana|    Ana|         30|
+----+-------+-------+-----------+

In [0]:
## Query  """"""

In [0]:
query2 = spark.sql("""
SELECT 
* 
FROM
data""")

In [0]:
display(query2)

age,name,newname,renamed_age
null,Fer,Fer,null
20,Michael,Michael,40
15,Ana,Ana,30